[package]
name = "weight_plot"
version = "0.1.0"
authors = ["wolpi <wolpi.dev@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
plotters = "0.3"
